import SystemSettings from "@/pages/systemseting/systemsetingFrom";

export const ROUTES = {
  auth: {
    login: "/auth/login",
    // register: "/auth/register",
    // registerStoreOwner: "/auth/register-store-owner",
    me: "/auth/me",
    logout: "/auth/logout",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
  },
  products: {
    getAll: "/products",
    getById: (id: string) => `/products/${id}`,
    create: "/products",
    update: (id: string) => `/products/${id}`,
    updateStatus: (id: string) => `/products/${id}/status`,
    delete: (id: string) => `/products/${id}`,
    bulkDelete: "/products/bulk-delete",
  },
  categories: {
    getAll: "/categories",
    getById: (id: string) => `/categories/${id}`,
    create: "/categories",
    update: (id: string) => `/categories/${id}`,
    updateStatus: (id: string) => `/categories/${id}/status`,
    delete: (id: string) => `/categories/${id}`,
    bulkDelete: "/categories/bulk-delete",
  },
  subcategories: {
    getAll: "/subcategories",
    getById: (id: string) => `/subcategories/${id}`,
    create: "/subcategories",
    update: (id: string) => `/subcategories/${id}`,
    updateStatus: (id: string) => `/subcategories/${id}/status`,
    delete: (id: string) => `/subcategories/${id}`,
    bulkDelete: "/subcategories/bulk-delete",
  },
  brands: {
    getAll: "/brands",
    getById: (id: string) => `/brands/${id}`,
    create: "/brands",
    update: (id: string) => `/brands/${id}`,
    updateStatus: (id: string) => `/brands/${id}/status`,
    delete: (id: string) => `/brands/${id}`,
    bulkDelete: "/brands/bulk-delete",
  },
  types: {
    getAll: "/types",
    getById: (id: string) => `/types/${id}`,
    create: "/types",
    update: (id: string) => `/types/${id}`,
    updateStatus: (id: string) => `/types/${id}/status`,
    delete: (id: string) => `/types/${id}`,
    bulkDelete: "/types/bulk-delete",
  },
  // fabrics: {
  //   getAll: "/fabrics",
  //   getById: (id: string) => `/fabrics/${id}`,
  //   create: "/fabrics",
  //   update: (id: string) => `/fabrics/${id}`,
  //   updateStatus: (id: string) => `/fabrics/${id}/status`,
  //   delete: (id: string) => `/fabrics/${id}`,
  //   bulkDelete: "/fabrics/bulk-delete",
  // },
  productLabels: {
    getAll: "/product-labels",
    getById: (id: string) => `/product-labels/${id}`,
    create: "/product-labels",
    update: (id: string) => `/product-labels/${id}`,
    updateStatus: (id: string) => `/product-labels/${id}/status`,
    delete: (id: string) => `/product-labels/${id}`,
    bulkDelete: "/product-labels/bulk-delete",
  },
  upload: {
    image: "/uploads/image",
  },
  discounts: {
    getAll: "/discounts",
    getById: (id: string) => `/discounts/${id}`,
    create: "/discounts",
    update: (id: string) => `/discounts/${id}`,
    updateStatus: (id: string) => `/discounts/${id}/status`,
    delete: (id: string) => `/discounts/${id}`,
    bulkDelete: "/discounts/bulk-delete",
  },
  coupons: {
    getAll: "/coupons",
    getById: (id: string) => `/coupons/${id}`,
    create: "/coupons",
    update: (id: string) => `/coupons/${id}`,
    updateStatus: (id: string) => `/coupons/${id}/status`,
    delete: (id: string) => `/coupons/${id}`,
    bulkDelete: "/coupons/bulk-delete",
  },
  orders: {
    getAll: "/orders",
    getById: (id: string) => `/orders/${id}`,
    create: "/orders",
    update: (id: string) => `/orders/${id}`,
    updateStatus: (id: string) => `/orders/${id}/status`,
    delete: (id: string) => `/orders/${id}`,
    bulkDelete: "/orders/bulk-delete",
    confirm: (id: string) => `/orders/${id}/confirm`,
    cancel: (id: string) => `/orders/${id}/cancel`,
    pack: (id: string) => `/orders/${id}/pack`,
    packingSlip: (id: string) => `/orders/${id}/packing-slip`,
    assignCourier: (id: string) => `/orders/${id}/assign-courier`,
    ship: (id: string) => `/orders/${id}/ship`,
    tracking: (id: string) => `/orders/${id}/tracking`,
    deliver: (id: string) => `/orders/${id}/deliver`,
    rto: (id: string) => `/orders/${id}/rto`,
    invoice: (id: string) => `/orders/${id}/invoice`,
  },
  payments: {
    getAll: "/payments",
    getById: (id: string) => `/payments/${id}`,
    delete: (id: string) => `/payments/${id}`,
    bulkDelete: "/payments/bulk-delete",
  },
  users: {
    getAll: "/users",
    getStoreCustomers: "/users/store/customers",
    getById: (id: string) => `/users/${id}`,
    create: "/users",
    update: (id: string) => `/users/${id}`,
    updateStatus: (id: string) => `/users/${id}/status`,
    delete: (id: string) => `/users/${id}`,
    bulkDelete: "/users/bulk-delete",
  },
  profile: {
    get: "/users/me",
    update: "/users/me",
  },
  settings: {
    get: "/settings",
    update: "/settings",
  },
  customerReviews: {
    getAll: "/customer-reviews",
    getById: (id: string) => `/customer-reviews/${id}`,
    delete: (id: string) => `/customer-reviews/${id}`,
    updateStatus: (id: string) => `/customer-reviews/${id}/status`,
    bulkDelete: "/customer-reviews/bulk-delete",
    update: (id: string) => `/customer-reviews/${id}`,
    getByProduct: (product_id: string) =>
      `/customer-reviews/product/${product_id}`,
  },
  cart: {
    getAll: "/carts",
    getById: (id: string) => `/carts/${id}`,
    delete: (id: string) => `/carts/${id}`,
    bulkDelete: "/carts/bulk-delete",
  },
  wishlist: {
    getAll: "/wishlists",
    getById: (id: string) => `/wishlists/${id}`,
    delete: (id: string) => `/wishlists/${id}`,
    bulkDelete: "/wishlists/bulk-delete",
  },
  contactUs: {
    getAll: "/contact-us",
    getById: (id: string) => `/contact-us/${id}`,
    delete: (id: string) => `/contact-us/${id}`,
    bulkDelete: "/contact-us/bulk-delete",
  },
  pages: {
    getAll: "/pages",
    getById: (id: string) => `/pages/${id}`,
    create: "/pages",
    update: (id: string) => `/pages/${id}`,
    updateStatus: (id: string) => `/pages/${id}/status`,
    delete: (id: string) => `/pages/${id}`,
    bulkDelete: "/pages/bulk-delete",
  },
  faqs: {
    create: "/faqs",
    getAll: "/faqs",
    getById: (id: string) => `/faqs/${id}`,
    update: (id: string) => `/faqs/${id}`,
    updateStatus: (id: string) => `/faqs/${id}/status`,
    delete: (id: string) => `/faqs/${id}`,
    bulkDelete: "/faqs/bulk-delete",
    saveBanner: "/faqs/banner",
    getBanner: "/faqs/banner/public",
  },

  navbar: {
    getAll: "/navbar",
    getById: (id: string) => `/navbar/${id}`,
    create: "/navbar",
    update: (id: string) => `/navbar/${id}`,
    updateStatus: (id: string) => `/navbar/${id}/status`,
    delete: (id: string) => `/navbar/${id}`,
    bulkDelete: "/navbar/bulk-delete",
  },
  footer: {
    getAll: "/footer",
    public: "/footer/public",
    getById: (id: string) => `/footer/${id}`,
    create: "/footer",
    update: (id: string) => `/footer/${id}`,
    updateStatus: (id: string) => `/footer/${id}/status`,
    delete: (id: string) => `/footer/${id}`,
    bulkDelete: "/footer/bulk-delete",
  },
  dashboard: {
    getData: "/dashboard",
  },
  stores: {
    getAll: "/stores",
    getById: (id: string) => `/stores/${id}`,
    create: "/stores",
    update: (id: string) => `/stores/${id}`,
    delete: (id: string) => `/stores/${id}`,
    bulkDelete: "/stores/bulk-delete",
    getMy: "/stores/my",
    updateMy: "/stores/my",
  },
  packing: {
    getAll: "/packing",
    getById: (id: string) => `/packing/${id}`,
    create: "/packing",
    update: (id: string) => `/packing/${id}`,
    updateStatus: (id: string) => `/packing/${id}/status`,
    delete: (id: string) => `/packing/${id}`,
    bulkDelete: "/packing/bulk-delete",
  },
  warehouse: {
    getAll: "/warehouses",
    create: "/warehouses",
    getById: (id: string) => `/warehouses/${id}`,
    update: (id: string) => `/warehouses/${id}`,
    updateStatus: (id: string) => `/warehouses/${id}/status`,
    delete: (id: string) => `/warehouses/${id}`,
    bulkDelete: "/warehouses/bulk-delete",
  },
  aboutPage: {
    get: "/about",
    getPublic: "/about/public",
    save: "/about",
    updateHero: "/about/hero",
    addContent: "/about/content",
    updateContent: (itemId: string) => `/about/content/${itemId}`,
    updateContentStatus: (itemId: string) => `/about/content/${itemId}/status`,
    deleteContent: (itemId: string) => `/about/content/${itemId}`,
    addFeature: "/about/feature",
    updateFeature: (featureId: string) => `/about/feature/${featureId}`,
    deleteFeature: (featureId: string) => `/about/feature/${featureId}`,
  },
  results: {
    getAll: "/results",
    getById: (id: string) => `/results/${id}`,
    create: "/results",
    update: (id: string) => `/results/${id}`,
    updateStatus: (id: string) => `/results/${id}/status`,
    delete: (id: string) => `/results/${id}`,
    bulkDelete: "/results/bulk-delete",
  },
  emails: {
    getAll: "/emails",
    getById: (id: string) => `/emails/${id}`,
    create: "/emails",
    update: (id: string) => `/emails/${id}`,
    delete: (id: string) => `/emails/${id}`,
    bulkDelete: "/emails/bulk-delete",
  },
  slider: {
    getAll: "/slide",
    getById: (id: string) => `/slide/${id}`,
    create: "/slide",
    update: (id: string) => `/slide/${id}`,
    updateStatus: (id: string) => `/slide/${id}/status`,
    delete: (id: string) => `/slide/${id}`,
    bulkDelete: "/slide/bulk-delete",
  },

  SystemSettings: {
    get: "/system-setting",
    update: "/system-setting",
  },
};
